Ngnix v1.11.3 and LibreSSL 2.5.5

diff --git a/Dockerfile.edge b/Dockerfile.edge
--- a/Dockerfile.edge
+++ b/Dockerfile.edge
@@ -1,8 +1,8 @@
 FROM alpine
 MAINTAINER Paul Pham <docker@aquaron.com>
 
-ENV _nginx=nginx-1.13.2 \
-    _libressl=libressl-2.5.4
+ENV _nginx=nginx-1.13.3 \
+    _libressl=libressl-2.5.5
 
 COPY data /data-default
 
@@ -19,9 +19,19 @@ RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
  && curl -fSL ${_nginx_uri} -o nginx.tar.gz \
  && curl -fSL ${_nginx_uri}.asc  -o nginx.tar.gz.asc \
  && export GNUPGHOME="$(mktemp -d)" \
- && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEYS" \
- && gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
- && rm -r "$GNUPGHOME" nginx.tar.gz.asc \
+ && found=''; \
+    for server in \
+        pgp.mit.edu \
+        hkp://keyserver.ubuntu.com:80 \
+        hkp://p80.pool.sks-keyservers.net:80 \
+        ha.pool.sks-keyservers.net \
+    ; do \
+        echo "Fetching GPG key $GPG_KEYS from $server"; \
+        gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+    gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+ && rm -rf "$GNUPGHOME" nginx.tar.gz.asc \
  && mkdir -p /usr/src \
  && tar -zxC /usr/src -f nginx.tar.gz \
  && rm nginx.tar.gz \
